// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANDGWFI7YBEWhq36RA-bsGWxfpTYu2tyg',
    appId: '1:952565689778:web:9c39b521ea71e33fd588ab',
    messagingSenderId: '952565689778',
    projectId: 'e-learning-students',
    authDomain: 'e-learning-students.firebaseapp.com',
    storageBucket: 'e-learning-students.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYaedyM3Vu6K7MmcYa50bPzGwjsPrLq7k',
    appId: '1:952565689778:android:eb88cbb7d3540383d588ab',
    messagingSenderId: '952565689778',
    projectId: 'e-learning-students',
    storageBucket: 'e-learning-students.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMo7BRD7zPTBAtnnNXM88F_byMrL1WF4',
    appId: '1:952565689778:ios:6b945ca5db8ca6c7d588ab',
    messagingSenderId: '952565689778',
    projectId: 'e-learning-students',
    storageBucket: 'e-learning-students.appspot.com',
    iosBundleId: 'com.example.studentsELearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANDGWFI7YBEWhq36RA-bsGWxfpTYu2tyg',
    appId: '1:952565689778:web:90b2fb4b29061782d588ab',
    messagingSenderId: '952565689778',
    projectId: 'e-learning-students',
    authDomain: 'e-learning-students.firebaseapp.com',
    storageBucket: 'e-learning-students.appspot.com',
  );
}
