// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaXI38NpKNMgr262GRwna7BEokOQlEvI',
    appId: '1:578325165964:web:9202390653ea21d69208a9',
    messagingSenderId: '578325165964',
    projectId: 'e-learning-12471',
    authDomain: 'e-learning-12471.firebaseapp.com',
    storageBucket: 'e-learning-12471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ATj9v0Tc0yYC3yYAy4ANAQNadBu9U0M',
    appId: '1:578325165964:android:ae80ec0f827404b59208a9',
    messagingSenderId: '578325165964',
    projectId: 'e-learning-12471',
    storageBucket: 'e-learning-12471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9N-6QLtmf4diO-xJStgxuHl5NhVP3-s',
    appId: '1:578325165964:ios:6b5de47c2815d23a9208a9',
    messagingSenderId: '578325165964',
    projectId: 'e-learning-12471',
    storageBucket: 'e-learning-12471.appspot.com',
    iosBundleId: 'com.example.studentsELearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdaXI38NpKNMgr262GRwna7BEokOQlEvI',
    appId: '1:578325165964:web:a211269477ccd9cb9208a9',
    messagingSenderId: '578325165964',
    projectId: 'e-learning-12471',
    authDomain: 'e-learning-12471.firebaseapp.com',
    storageBucket: 'e-learning-12471.appspot.com',
  );
}
